### ISSUE TITLE
Abfrage für lokales Verbinden über VPN

### ISSUE THREAD

**Issue by MrLee99** [foxriver76/ioBroker-Visu-App#12]
Moin!

Kann man das Feature deaktivierbar machen in den Settings?
Hintergrund: Ich verwende auf dem Handy Blokada welches ein VPN darstellt ...aber natürlich keinen Zugriff aus Heimnetzwerk tunnelt. :-)
Würde mir einen Fingertipp sparen wenn ich starte :-)

Danke 
Mr.Lee

**Comment by foxriver76** [comment]
Will be included in the next version
