### ISSUE TITLE
[FEATURE] Open target `_blank` links in browser

### ISSUE THREAD

**Issue by foxriver76** [foxriver76/ioBroker-Visu-App#15]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Feature description

At least on iOS this is not done by default. The problem is, we cannot detect if the navigation change comes from such links or not - need to wait until https://github.com/react-native-webview/react-native-webview/pull/2640 is implemented

**Comment by RK62** [comment]
Why not using the simple solution of the old app and implementing a switch for browser selection? 
I don't want to decide it per window, external links should always be opened in Safari for compatibility reasons.

**Comment by foxriver76** [comment]
The problem is, that we can currently not detect for sure, if it is an external link.The only heuristic I can think of, is to check if the `base url` is not contained.

**Comment by RK62** [comment]
The approach "base url" sounds very pragmatic. This can be further improved at a later time.

**Comment by foxriver76** [comment]
Part of 1.0.21

**Comment by RK62** [comment]
Thanks, works fine!

**Comment by RK62** [comment]
In Version 1.0.28 external links again are opened in the app and not in Safari.

**Comment by foxriver76** [comment]
Ah while migrating to a new version of expo, it downgraded the webview package, will be fixed in next version - sorry

**Comment by RK62** [comment]
No problem, thanks for your excellent work!

**Comment by foxriver76** [comment]
hopefully works again

**Comment by RK62** [comment]
Works fine as before! 
Thank you very much!
