### ISSUE TITLE
IOS: Add possibility to have multiple instances to different projects

### ISSUE THREAD

**Issue by KoMa1978** [foxriver76/ioBroker-Visu-App#16]
Hi,

it would be great to have an option to simply switch from one vis project to another, probably by putting Shortcuts on the Home screen or if pressing long on the HomeScreen Icon.

At the moment it is very complicated to switch from one view to another.

Thanks a lot,

**Comment by foxriver76** [comment]
Basically an interesting idea. What do you mean by „home screen“? App Start Screen with eg drop-down if multiple projects are defined?

**Comment by KoMa1978** [comment]
Yes. AFAIK there can be two solutions:

1.  long push on the icon and a drop down pops up with all configured projects (and a settings option to reach configuration instead of 3finger click) (like it is possible with chrome or mail or …)
2. Add a shortcut to the Home Screen like it is possible in Safari

**Comment by foxriver76** [comment]
Implementation Notes

Resources:
https://www.npmjs.com/package/@config-plugins/react-native-quick-actions

https://www.npmjs.com/package/react-native-quick-actions

Not sure if this is still the way to go, as the library looks unmaintained.

**Comment by foxriver76** [comment]
I am currently implementing this (for now 2 projects supported, however the approach can easily be adapted to more projects), if you want to provide me your Apple ID I would love to invite you to Test Flight.

**Comment by KoMa1978** [comment]
I’d like to but how can I send you my ID without posting it here?

**Comment by foxriver76** [comment]
https://testflight.apple.com/join/UWrb8L7e

**Comment by KoMa1978** [comment]
Looks very good. A possibility to rename a project and to change the order would be great.

**Comment by KoMa1978** [comment]
And maybe select which project should be opened at App start and not open Standard as default.

**Comment by foxriver76** [comment]
Will be part of 1.0.18 (renaming also supported) everything else will come later if demand is high enough

**Comment by KoMa1978** [comment]
One more thing: can you please add a function to remove all leading and trailing spaces from text input field before saving? I had it a couple of times that there was a trailing space resulting in a URL ending with %20

**Comment by KoMa1978** [comment]
Thanks a lot for the great work.

**Comment by foxriver76** [comment]
For URLs, this would probably make sense to fix this yes.

**Comment by KoMa1978** [comment]
Please remove leading and trailing spaces also in the project name. This is similar to a URL and having them in the name will lead to %20 in the connection

**Comment by KoMa1978** [comment]
Hi, can you probably add up to 5 projects that can be opened? That would be great. Thanks a lot!

**Comment by foxriver76** [comment]
It will be increased to 3 in the next version (1.0.20 coming soon) with some additional feature coming in this version.
