### ISSUE TITLE
[FEATURE] Configure default background color

### ISSUE THREAD

**Issue by KoMa1978** [foxriver76/ioBroker-Visu-App#17]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Feature description

During a reconnect the background always turns white. The color should be configurable.

Especially in dark mode VIS the white background color is „disturbing“.

**Comment by foxriver76** [comment]
basically, this is very specific to vis and would be better fixed in the adapter, however, the reconnect now applies the dark mode settings from the app up from 1.0.28
