### ISSUE TITLE
Gerät entweder remote oder via Einstellung automatisch neu starten

### ISSUE THREAD

**Issue by peoples0815** [foxriver76/ioBroker-Visu-App#18]
### Feature description

Gibt es die Möglichkeit das Gerät entweder remote oder via App-Einstellung einmal am Tag neu durch zu starten?
Wenn nicht wäre es toll wenn man sowas (wie bei Fully) einbauen könnte.

Hintergrund:
Gefühlt werden Geräte (Android Wandtablets die rund um die Uhr laufen) über die Zeit träger, und auch geänderte Einstellungen in der Vis bräuchte man so nicht händisch laden, sondern sie würden einfach einmal am Tag neu geladen.

**Comment by foxriver76** [comment]
Ich vermute, da musst du leider auf so etwas wie Tasker o. ä. ausweichen, was das ein mal am Tag machen kann. Das wird nicht einfach so möglich sein, Fully macht da ja sehr viel, so dass die App ein alternativer Launcher ist etc. das übersteigt die Pläne für diese App hier derzeit. Und für iOS wir das vermutlich gar unmöglich sein.

**Comment by peoples0815** [comment]
Alles kar, war nur eine Idee

Trotzdem sehr tolles Projekt!
