### ISSUE TITLE
[BUG] Controlling brightness of iOS devices with vis does not work 

### ISSUE THREAD

**Issue by foxriver76** [foxriver76/ioBroker-Visu-App#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Controlling the brightness while using vis as application does not work for iOS devices

### Expected Behavior

It should work same as on Android platform

### Steps To Reproduce

1. Activate brightness sync in settings
2. Start runtime in app
3. Try to control brightness via the ioBroker state
4. Devices brightness won't change

### Which OS are you using?

iOS

### OS Version

16.3.1

### Device

iPhone 14

### App Version

1.0.9

### Anything else?

We probably need to request permissions on iOS

**Comment by foxriver76** [comment]
Will be fixed in 1.0.10

**Comment by Standarduser** [comment]
Funktioniert, vielen Dank

**Comment by foxriver76** [comment]
Mit brightness wert meinst du der State repräsentiert nicht die Helligkeit vom Gerät sondern einen alten wert?

**Comment by Standarduser** [comment]
Ja, das meinte ich. Wenn man den State verändert hat, als die App nicht im Vordergrund war, dann steht der gesetzte Wert weiterhin als unbestätigt da, manchmal wird jedoch auch 0% als bestätigter Wert angezeigt, obwohl die Helligkeit am Gerät auf 50% steht. 

Dieses Verhalten hab ich bei einem iPad festgestellt und vermute, dass es Abhilfe schaffen würde, den Wert kurz nach dem Start der App an ioBroker zu senden.

**Comment by foxriver76** [comment]
In der nächsten Version werden sämtliche aktivierten Synchronisierungsstates nach dem Socket reconnect, erneut gesendet, da sie out of sync sein könnten.
