### ISSUE TITLE
app startet nicht bei VPN

### ISSUE THREAD

**Issue by bahnuhr** [foxriver76/ioBroker-Visu-App#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which OS are you using?

Android

### OS Version

14

### Device

xiaomi mi 11

### App Version

1.0.20

### Anything else?

Wenn ich im Heimnetz bin (und vpn aus ist) funktioniert dies einwandfrei.
Wenn ich von außen drauf zugreife (ohne vpn) dann funktioniert pro auch einwandfrei (halt ohne cam Bilder - weil fixe IP).
Wenn ich aber vpn einschalte dann kommt (wenn es richtig läuft) die Abfrage "soll man auf die interne IP zugreifen" (oder so ähnlich.
Dieser workflow funktioniert aber nicht zuverlässig. Sehr sehr oft passiert gar nichts. Der Bildschrim bleibt dann weiß.

**Comment by bahnuhr** [comment]
Ich habe immer noch das Problem, dass bei bestehendem VPN nur der weiße Hintergrund kommt. Die Abfrage nach "Aufruf lokaler URL" kommt nicht.
Lösungsvorschlag:
Bitte bei den Einstellungen einen Punkt aufnehmen "immer mit lokaler URL starten" (oder ähnlich).
Damit könnte der workflow der Erkennung von vpn umgangen werden und sofort die interne lokale URL aufgerufen werden.
Wäre doch bestimmt eine Lösung.
mfg
Dieter

**Comment by foxriver76** [comment]
Was heißt immer mit lokaler url starten? Dann wird er extern kein Pro anziehen

**Comment by bahnuhr** [comment]
Doch, in dem dieses Feld wieder deaktivierst.
Fazit derzeit:
Die vpn erkennung klappt in 9 von 10 Fällen nicht.

**Comment by foxriver76** [comment]
naja wenn extern deaktiviert ist, sollte er sowieso ohne vpn abfrage lokal aufrufen, da das die einzige möglichkeit ist.

**Comment by bahnuhr** [comment]
Ne, das klappt nicht.
Er versucht vpn zu finden und findet dies nicht. 
Fazit ist dann:
weißer Bildschirm, und es tut sich nichts mehr.

Ein Punkt:
"VPN ist an" oder wie oben "immer lokal .. aufrufen" wäre aus meiner Sicht das einfachste.
Würde die nicht nicht funktionierende vpn erkennung halt umgehen.

**Comment by bahnuhr** [comment]
Hallo,
Wäre es aus deiner Sicht eine Lösung einen solchen Punkt einzufügen.
Oder findest du dies gar nicht gut.

Fazit ist bei mir weiterhin:
von 10 Versuchen findet 9 mal die app nicht das bestehende vpn. Der bildschirm bleibt dann weiß und die Abfrage "Starten mit lokaler vpn" kommt nicht.

**Comment by foxriver76** [comment]
Ich habe in der neuen Version nochmal 2 Sachen eingebaut, ein mal wenn sich der Render Prozess auf Android verabschiedet, wird der webview nun neu geladen, statt bislang ein weißer Bildschirm kam, wobei ich nicht weiß wie oft das tatsächlich die Ursache war. Und wie in https://github.com/foxriver76/ioBroker-Visu-App/issues/12 gewünscht, kann man VPN Erkennung deaktivieren - in kommender Version 1.0.27

**Comment by bahnuhr** [comment]
Hallo,
installiert habe ich nun die 1.0.28
VPN Erkennung ausgeschaltet.

Situation:
VPN auf dem Handy ist an (verbunden mit dem Heimnetz)
Wifi ist an (verbunden mit einem Fremdnetz)
Aufruf der app:
Es kommt nur ein weißer Bildschirm !

Fazit:
Keine Verbesserung mit der Abschaltung der VPN Erkennung

**Comment by foxriver76** [comment]
Dann zeig mal deine Settings bitte. Insbesondere was bei Extern gewählt ist. Daran wird entschieden worauf zugegriffen wird.

**Comment by bahnuhr** [comment]
Extern:
ProCloud
Name: dieter@...
passwort: ...
WLAN SSID: Mueller
VPN Erkennung aus.

Er greift aber nicht auf die pro zu.
Sondern der Bildschirm friert ein.

Deshalb fand ich meine Idee:
Schaltfläche: immer auf lokale ip zugreifen ganz gut.
(also wenn vpn manuell eingeschaltet wurde und ein Fremdnetz besteht; dann trotzdem die lokale ip aufrufen).

**Comment by bahnuhr** [comment]
Und eben kam die Abfrage "möchten sie lokal zugreifen, VN erkannt" wieder 
(obwohl ja Erkennung ausgeschaltet ist).

**Comment by foxriver76** [comment]
ich fände es gut, wenn er auf Pro zugreift, da so konfiguriert. D.h. im allgemeinen geht Pro Zugriff mit der App nicht bei dir?

**Comment by bahnuhr** [comment]
vpn aus:
zugriff auf pro klappt einwandfrei
vpn ein:
weißer bildschirm, eingeforen
dann kam eben wieder (vpn erkannt) obwohl vpn erkennung ausgeschaltet wurde.

Fazit:
Wenn vpn aus klappt alles so wie es soll. Also zuhause mit lokaler url und sonst mit pro.

**Comment by bahnuhr** [comment]
> Weil wenn VPN Detektierung nicht läuft, müsste er ja Pro wählen und das geht eigentlich?

Ja, und da hätte ich gerne, dass er trotzdem die lokale url aufruft.
Weil vpn von mir manuell gestartet wurde.
Deshalb ja der Button Wunsch: "immer auf lokale url zugreifen"

(oder übertreibe ich jetzt ?)

**Comment by foxriver76** [comment]
Kannst du mit der 1.0.29 mal testen ob er dich immer noch fragt obwohl deaktiviert?

**Comment by bahnuhr** [comment]
deaktiviert: Abfrage kam jetzt nicht mehr.
Scheint richtig zu sein.

Eben kam die Abfrage: "Wlan ssid Erkennung ist deaktiviert"
Wo kam die jetzt her ?

**Comment by bahnuhr** [comment]
Hallo,
habe einen workaround für mich gefunden.
Da ich meistens vpn an habe, habe ich bei extern auch die lokale url eingetragen.
Und vpn erkennung aus.

Klappt einwandfrei.
Also für mich insofern erledigt.
