### ISSUE TITLE
HTML input tags are not translated

### ISSUE THREAD

**Issue by ice987987** [foxriver76/ioBroker-Visu-App#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

(At least) The following HTML input tags are not translated:

- `<input type="date">`
- `<input type="datetime-local">`
- `<input type="month">`

f.ex. `<input type="date">` in ioBroker-Visu-App:
![IMG_0285](https://github.com/foxriver76/ioBroker-Visu-App/assets/69053781/7c36471e-34dd-408c-a944-b3013e5401b2)

### Expected Behavior

translate Input tags to device langage

f.ex. `<input type="date">` in iPad Safari:
![IMG_0284](https://github.com/foxriver76/ioBroker-Visu-App/assets/69053781/e27668dd-415d-4fa2-af0c-602892a54ab9)

### Steps To Reproduce

import the following widet in ioBroker.vis:

`[{"tpl":"tplHtml","data":{"g_fixed":false,"g_visibility":false,"g_css_font_text":false,"g_css_background":false,"g_css_shadow_padding":false,"g_css_border":false,"g_gestures":false,"g_signals":false,"g_last_change":false,"visibility-cond":"==","visibility-val":1,"visibility-groups-action":"hide","refreshInterval":"0","signals-cond-0":"==","signals-val-0":true,"signals-icon-0":"/vis/signals/lowbattery.png","signals-icon-size-0":0,"signals-blink-0":false,"signals-horz-0":0,"signals-vert-0":0,"signals-hide-edit-0":false,"signals-cond-1":"==","signals-val-1":true,"signals-icon-1":"/vis/signals/lowbattery.png","signals-icon-size-1":0,"signals-blink-1":false,"signals-horz-1":0,"signals-vert-1":0,"signals-hide-edit-1":false,"signals-cond-2":"==","signals-val-2":true,"signals-icon-2":"/vis/signals/lowbattery.png","signals-icon-size-2":0,"signals-blink-2":false,"signals-horz-2":0,"signals-vert-2":0,"signals-hide-edit-2":false,"lc-type":"last-change","lc-is-interval":true,"lc-is-moment":false,"lc-format":"","lc-position-vert":"top","lc-position-horz":"right","lc-offset-vert":0,"lc-offset-horz":0,"lc-font-size":"12px","lc-font-family":"","lc-font-style":"","lc-bkg-color":"","lc-color":"","lc-border-width":"0","lc-border-style":"","lc-border-color":"","lc-border-radius":10,"lc-zindex":0,"html":"<input type=\"date\" id=\"date\">\n<br>\n<input type=\"datetime-local\" id=\"datetime-local\">\n<br>\n<input type=\"month\" id=\"month\">"},"style":{"left":"0px","top":"0px","width":"100%","z-index":"0"},"widgetSet":"basic"}]`

### Which OS are you using?

iOS

### OS Version

16.6

### Device

iPad Pro

### App Version

1.0.21

### Anything else?

-

**Comment by foxriver76** [comment]
will be fixed in 1.0.24

**Comment by foxriver76** [comment]
1.0.24 released
