### ISSUE TITLE
[FEATURE] Adaptive Icons

### ISSUE THREAD

**Issue by dontobi** [foxriver76/ioBroker-Visu-App#25]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Feature description

Ich nutze die App auf meinem Google Pixel 6 sehr gerne, jedoch würde ich mir den Support für die Adaptive Icons wünschen. Mehr dazu unter: [https://developer.android.com/develop/ui/views/launch/icon_design_adaptive](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)

Vielleicht könnte dann auch der Support für Themed Icons implementiert werden. Mehr dazu unter: [https://developer.android.com/about/versions/13/features#themed-app-icons](https://developer.android.com/about/versions/13/features#themed-app-icons)

### Anything else?

Nichts

**Comment by foxriver76** [comment]
I unfortunately could not test it, but should hopefully be working with v1.0.24

**Comment by dontobi** [comment]
Ich würde das Issue noch einmal öffnen wollen. Die Icons haben sich verändert, jedoch werden diese immernoch nicht sauber angezeigt. Siehe Screenshot (Version 1.0.0.24).

![Screenshot_20230829-203559.png](https://github.com/foxriver76/ioBroker-Visu-App/assets/19261667/f6d59f77-3dd2-4e14-b16b-97b47bdf3f3b)

**Comment by foxriver76** [comment]
Can you show the icon on the homescreen. The generated files look different from the one shown.

**Comment by dontobi** [comment]
![Screenshot_20230830-062757](https://github.com/foxriver76/ioBroker-Visu-App/assets/19261667/fde34f34-dedc-48eb-9738-e0d44fb6f10d)
![Screenshot_20230830-062820](https://github.com/foxriver76/ioBroker-Visu-App/assets/19261667/f9e7c0f4-1dfa-4c40-a780-60a7331cf15e)

**Comment by foxriver76** [comment]
Icons sind angepasst sollte in nächster version passen

**Comment by foxriver76** [comment]
1.0.25 auf dem Weg, damit sollte es hoffentlich passen
