### ISSUE TITLE
[BUG] vis-2-beta

### ISSUE THREAD

**Issue by csicom** [foxriver76/ioBroker-Visu-App#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Please change path vis-2-beta to vis-2, because vis 2 was released. 

### Which OS are you using?

Android

### OS Version

newest

### Device

all

### App Version

newest

**Comment by foxriver76** [comment]
1.0.25 on the way, you have to manually change to vis-2 with the new version

**Comment by csicom** [comment]
In version 1.0.25 I get all times: 

Error loding page
Domain: undefined
Error Code: -1
Description net: ERR_CLEARTEXT_NOT_PERMITTED

it´s the same in another old vis -project on this app.

**Comment by foxriver76** [comment]
No idea what went wrong in the published version, I try to build a new one

**Comment by foxriver76** [comment]
Hotfix on the way. We have upgraded lots of internal dependencies, and some defaults changed, so http access was possible during testing but not on production builds.
