### ISSUE TITLE
[BUG] After todays update. Only loading

### ISSUE THREAD

**Issue by dklueh79** [foxriver76/ioBroker-Visu-App#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After todays update. The app is only loading. 
Nothing changed since prev Version.
Using latest jarvis.

S23 with A135.15.78

### Steps To Reproduce

Loading app, no jarvis board

### Which OS are you using?

Android

### OS Version

13

### Device

S23

### App Version

Latest

**Comment by dklueh79** [comment]
![Uploading Screenshot_20230908_213913_ioBroker Visu.jpg…]()

**Comment by foxriver76** [comment]
should be fixed in 1.0.28
