### ISSUE TITLE
[FEATURE] GPS Daten an ioBroker DPs senden

### ISSUE THREAD

**Issue by tritanium73** [foxriver76/ioBroker-Visu-App#30]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Feature description

Bitte eine Option einbauen, das die GPS Koordinaten an einen eigenen Datenpunkt gesendet werden.

-> In den Einstellungen der App eine Möglichkeit schaffen, einen Datenpunkt festzulegen, an den dann die Coords gesendet werden.

z.b.:    `0_userdata.0.Testpunkte.phone_micha`

Somit wäre es möglich die GPS Daten der App(s) auch für "nicht-VIS" Nutzer zu verwenden.

lg Micha

**Comment by foxriver76** [comment]
It might be good to create all datapoints somewhere which exists for all installations. So e.g. in `web` namespace but then maybe need to make the web instance configurable as it could be possible that `0` is non existing.

**Comment by cavernerg** [comment]
as iot is the only needed adapter , this would be the obvious choice. All individual DPs can then be done by alias

**Comment by foxriver76** [comment]
Yes this is now redundant as in future relevant data will be sent to iot
