### ISSUE TITLE
[FEATURE] Support für HabPanel hinzufügen 

### ISSUE THREAD

**Issue by bastian-mer** [foxriver76/ioBroker-Visu-App#31]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Feature description

Support für den ioBroker-Adapter für die Visualisierung mit HabPanel hinzufügen

Url Cloud:
https://iobroker.pro/habpanel/index.html

Url lokal:
http://IP:8082/habpanel/index.html

**Comment by bastian-mer** [comment]
Ich kann bei Bedarf gerne testen.

**Comment by foxriver76** [comment]
1.0.31 will support HABPanel
