### ISSUE TITLE
[FEATURE] Backup Settings

### ISSUE THREAD

**Issue by KoMa1978** [foxriver76/ioBroker-Visu-App#32]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Feature description

Please add an option to backup/export settings.

I got a new iPhone and had to set up the app again.

Backup should be done automatically preferable to configurable destinations like iCloud or a local file.
Export manually should be possible as well.

Thanks a lot,
 KoMa1978

**Comment by foxriver76** [comment]
Data is stored via `AsyncStorage` which writes to the `Apllication Support` directory. This is automatically saved to iCloud backups. So the quesiton here would be if you restored a backup or just reinstalled the app on the new Phone afterwards.

**Comment by KoMa1978** [comment]
I got a new iPhone and used the standard IOS feature to migrate all the settings.

This worked fine for other apps but the Visu app was installed without any settings.

**Comment by KoMa1978** [comment]
Very interesting would also be a manual import/export of the settings to easily set up the app for example if I create a new project and want to deploy it to our iPhones/iPads

**Comment by foxriver76** [comment]
https://react-native-async-storage.github.io/async-storage/docs/advanced/backup/

**Comment by foxriver76** [comment]
1.0.31 will automatically backup data
