### ISSUE TITLE
[BUG] Falscher Zuordnung über ioBroker.pro

### ISSUE THREAD

**Issue by cn72** [foxriver76/ioBroker-Visu-App#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Ich habe 3 Unterschiedliche VIS (Privat / Büro / Verein). Bin ich im jeweiligen WLAN klappt alles für den lokalen Aufruf. Sobald ich über ioBroker.pro zugreifen möchte, funktioniert nur noch der 'Standard' Zugriff (die ersten Zugangsdaten für den Pro Account). Bei den anderen beiden kommt die Fehlermeldung, das die VIS nicht existiert. Sieht so aus, dass bei den anderen beiden die Zugangsdaten nicht genutzt werden. Nutze die Android App.

### Which OS are you using?

Android

### OS Version

13

### Device

Samsung S20FE

### App Version

1.0.31

**Comment by foxriver76** [comment]
Probier das bitte nochmal wenn 1.0.32 erschienen ist, in die Richtung wurde auch etwas gefixt.

**Comment by cn72** [comment]
Heute kam 1.0.33, aber leider keine Änderung.
Benutze 3 unterschiedliche Vis's (Arbeit / Privat / Verein). Alle haben einen anderen iobroker.pro Account. Die Arbeits-Vis ist die Standard Vis, welche sich öffnet, wenn ich die App direkt öffne. Hier klappt es auch, wenn ich Mobile Daten nutze, bzw. wenn ich in einem WLAN bin.
Die Private Vis bzw. die Verins Vis funktionieren nur, wenn ich in dem richtigen WLAN bin, ansonsten kommt die Meldung, dass die VIS auf dem Server nicht vorhanden ist.
Das schaut für mich so aus, dass beim Verbindungsaufbau immer nur der Pro-Account der Standard (hier Arbeit) VIS genommen wird.

**Comment by foxriver76** [comment]
Kannst du mal einen Screenshot der Fehlermeldung bereitstellen?

**Comment by cn72** [comment]
![Screenshot 2024-02-12 192356](https://github.com/foxriver76/ioBroker-Visu-App/assets/75731455/4d03ec40-065a-451b-bd9a-b8a467763b97)

**Comment by foxriver76** [comment]
Anscheinend löscht die App nicht die Cookies und ist dann noch im alten Pro Account. Es scheint jetzt bei mir lokal zu funktionieren, ich werde die Tage  nochmal eine neue Version machen.

**Comment by foxriver76** [comment]
Ist es mit 1.0.34 besser geworden?

**Comment by cn72** [comment]
Nein, leider nicht. Jetzt kann gar keine Verbindung zu irgendeiner VIS über iobroker.pro aufgebaut werden.
Lokal im WLAN funktioniert es.

**Comment by foxriver76** [comment]
Was für ein Fehler kommt denn?

**Comment by cn72** [comment]
nichts, einfach nur ein weißer Bildschirm. Oben rechts steht der Hinweis .pro.

**Comment by cn72** [comment]
so, jetzt wird es tricky....
Wenn ich mit den 3 Fingern den weißen Bildschirm berühre wird manchmal die richtige VIS geladen, manchmal komme ich in die Einstellungen. Wenn ich die Einstellungen verlasse, wird die passende VIS geladen.

**Comment by cn72** [comment]
wenn ich den Cache der App auf dem Samsung lösche, funktioniert das einmal für die Aufgerufene VIS. Wenn ich dann die App schließe und eine andere VIS aufrufen möchte, muss ich vorher den Cache auf dem Telefon wieder löschen.

**Comment by foxriver76** [comment]
Hm.. habs jetzt extra mal auf einem Android (Pixel 2) mit zwei Pro Accounts gemacht, da funktioniert es bei mir und auf iPhone auch.

Ich verstehe vom Code her aktuell auch nicht wo er sich bei dir verschluckt, es werden beim Neustart der App sowie beim Projektwechsel die Cookies gelöscht und dann sollte eigentlich alles auf 0 sein, aber irgendwas scheint er bei dir ja noch zu cachen..

**Comment by cn72** [comment]
wenn bei mir der Bildschirm weiß bleibt ( also eigentlich immer, es sei denn ich habe den Cache manuell gelöscht) , brauche ich nur in die Einstellungen gehen und ohne eine Änderung auf verlassen klicken. dann wird alles normal und richtig geladen. Irgendwie scheint da die Routine anders zu sein als beim Start... ?

**Comment by foxriver76** [comment]
KAnnst du mal die APK probieren https://easyupload.io/oj71wx

**Comment by cn72** [comment]
Hab die APK installiert, leider keine Änderung. Version steht auf 1.0.34

**Comment by foxriver76** [comment]
Unten in den settings hast du 1.0.34 stehen?

**Comment by cn72** [comment]
genau

**Comment by foxriver76** [comment]
Hm okay evtl habe ich dir ne alte Version gebaut ich schaue später nochmal

**Comment by foxriver76** [comment]
Das sollte eine 1.0.36 sein https://easyupload.io/92ntc4

**Comment by cn72** [comment]
![Screenshot 2024-02-15 181952](https://github.com/foxriver76/ioBroker-Visu-App/assets/75731455/c0502dd3-f082-4044-b88e-fbfdab457cd1)

**Comment by cn72** [comment]
Muss ich die andere Version erst deinstallieren ?
Der Fehler kam auch schon beim ersten APK Download, da ist es mir allerdings nicht aufgefallen ....

**Comment by foxriver76** [comment]
Ah Android.. ja ist so. hm ich vermute dann müsstest du alles neu konfigurieren. Ich kann auch nochmal testen und es offiziell releasen.

**Comment by cn72** [comment]
github@lvwa.de

**Comment by foxriver76** [comment]
hm die mag er nicht, ich vermute er braucht die von deinem play store konto oder eine von einem gültigen google account.

**Comment by foxriver76** [comment]
kannst sie mir auch privat schicken falls sie hier nicht stehen soll an moritz.heusinger@gmail.com

**Comment by foxriver76** [comment]
Also lt Google ist es jetzt freigegeben

**Comment by cn72** [comment]
Hab grade nachgeschaut, hab jetzt ein Update 1.0.35

Eine Mail von google hab ich nicht bekommen.

 

Bei der 1.0.35 hat sich nichts geändert. Verbindung über iobroker.pro nur wenn der Cache geleert wurde oder einmal in die Einstellungen und wieder verlassen.

 

Mir ist da noch ein Phänomen aufgefallen:
ich habe auf der vis von zu Hause ein basic-Image, welches sichtbar wird, wenn ein Bluetooth Verbindung mit dem Autoradio vorhanden ist. Die Steuerung über die iobroker.pro Verbindung funktioniert. Bin ich im WLAN zu Hause, wird mir das Logo immer angezeigt. 

Wenn ich den Cache leere, funktioniert es einmal bei der lokalen WLAN Verbindung. Nach erneutem Starten der App ist das basic-Image wieder permanent sichtbar.

Keine Ahnung, ob das im Zusammenhang steht.

 

Von: Max Hauser ***@***.***> 
Gesendet: Sonntag, 18. Februar 2024 13:06
An: foxriver76/ioBroker-Visu-App ***@***.***>
Cc: Christoph Nienhausen ***@***.***>; Author ***@***.***>
Betreff: Re: [foxriver76/ioBroker-Visu-App] [BUG] Falscher Zuordnung über ioBroker.pro (Issue #36)

 

Also lt Google ist es jetzt freigegeben

**Comment by cn72** [comment]
Folgende Meldung von Google beim Aufruf des Links:
App not available for this account
Your account isn't currently eligible for this app's testing program.

**Comment by foxriver76** [comment]
ne wird die 10.36 sein, das updaten der tester wird auch nochmal geprüft :roll_eyes:

**Comment by foxriver76** [comment]
Geht es jetzt via https://play.google.com/apps/testing/com.iobroker.visu 1.0.36 zu installieren?

**Comment by cn72** [comment]
Konnte jetzt die Einladung annehmen. In den App-Infos wird angezeigt, dass ich Beta-Tester bin. Das hat schon mal geklappt.  Muss noch etwas warten, bis das Update angezeigt wird

**Comment by cn72** [comment]
Habe jetzt die 1.0.36 installieren können. Leider keine Änderung.
Im loakalen Netzwerk kann die zugehörige VIS angezeigt werden. Über die iobroker.pro Verbindung bekomme ich immer einen weißen/leeren Bildschirm (egal ob über die lokale Internetverbindung oder über mobile Daten).Muss dann mit den 3 Fingern das Menü aufrufen und gehe direkt auf verlassen, dann wird die vis geladen und alles funktioniert.

**Comment by cn72** [comment]
![Logo](https://github.com/foxriver76/ioBroker-Visu-App/assets/75731455/adfeae42-8edc-4112-a933-c8cb08df78f0)
Wenn ich die App starte und eine Verbindung via iobroker.pro nutzen will, erschein erst das Logo, dreht sich um ca 90 Grad, startet dann von neumem, dreht sich wirder um ca 90 Grad, damm kommt der weiße Bildschirm und ich muss das Menü aufrufen.
Nachdem verlasse des Menüs erscheint das Logo wieder, dreht sich um ca. 180-270 Grad, dann erscheint die Connection und Loading meldung und die VIS wird angezeigt.

**Comment by cn72** [comment]
Das Neuladen mit 2 Fingern funktioniert....(bei allen drei VIS)

**Comment by foxriver76** [comment]
Es ist eine 1.0.36 zur Überprüfung eingereicht. Ich hoffe es bringt Besserung.

**Comment by cn72** [comment]
Hab das Update grade installiert, leider keine Änderung.
Bei allen 3 VIS nach dem Start der APP weißer Bildschirm, dann mit 2 Fingern Doppelclick, alles OK.
Hab dann mal WLAN eingeschaltet, APP gestartet, lokale VIS aufgerufen, wurde auch sofort angezeigt. Dann das WLAN ausgeschaltet. APP schaltet um (Bild siehe unten). Doppelklick mit 2 Fingern, Verbindung klappt.
![Bild](https://github.com/foxriver76/ioBroker-Visu-App/assets/75731455/8fa7a372-f08a-42ca-989a-be3f76efdefa)

**Comment by cn72** [comment]
Angezeigt wird 1.0.36, ich hatte die Updates in der GooglePlay App abgefragt/aktualisiert und wurde mir vorhin angezeigt.
Für mich sieht das irgendwie so aus, dass beim ersten Verbindungsaufbau übers Internet irgend etwas nicht klappt.
Wenn ich iobroker.pro im Browser aufrufe kommt ein Redirect auf iobroker.pro/www. Wenn auch die App darüber die Verbindung aufgebaut und das beim ersten Aufbau nicht mitbekommt könnte ich mir das Verhalten erklären. Das Telefon zeigt mir 193kb im Cache an, bevor ich mit den 2 Finger den Doppelklick mache

**Comment by foxriver76** [comment]
Hast du ein anderes Gerät mit dem du mal testen kannst oder magst du mal neu installieren? Ich wüsste nicht mehr woran es liegen sollte

**Comment by foxriver76** [comment]
Und zeig mal bitte noch Einstellungen eines der Web Adapter die für pro genutzt werden

**Comment by cn72** [comment]
Hab das gerade mal am Tablet ausprobiert zu Hause. WLAN ok. Über HotSpot vom Mobiltelefon über Mobile Daten das selbe Verhalten. Ist ein Samsung Tab A7 mit Android 12 und der Beta App.
Welche Einstellungen meinst du genau ?
Komme da heute nicht mehr zu, muss noch gleich los..... Schicke ich dann morgen

**Comment by foxriver76** [comment]
Hm wieso Beta App? Die offizielle 1.0.36 aus dem Play Store bitte probieren. Bzgl Web Adapter Insbesondere die Einstellung ob socketio oder websockets am besten Screenshot

**Comment by cn72** [comment]
Ist der gleiche Google Account am Tablet, deswegen Beta
![tablet](https://github.com/foxriver76/ioBroker-Visu-App/assets/75731455/92a380d4-8c2e-492a-a7a2-47e150fdc964)
![screeshot](https://github.com/foxriver76/ioBroker-Visu-App/assets/75731455/a873da60-70aa-421a-a9d0-5d9bfc99e729)

Hier der Screenshot bei mir zu Hause.
Beim iobroker auf der Arbeit ist der Haken bei reine Web-Sockets entfernt.

**Comment by foxriver76** [comment]
Puh aber heißt du kannst die offizielle Version gerade nicht installieren? Das wirkt irgendwie als wäre das dann die Testversion.

**Comment by foxriver76** [comment]
Und wenn du die App ein mal gestartet hast und dann per quick actions (App nur im Hintergrund nicht beendet) ein anders Projekt öffnest, lädt dann auch nichts?

**Comment by cn72** [comment]
Also, ich starte das Projekt zu Hause über mobile Daten. Damit es angezeigt wird muss ich den Doppelklick mit 2 Fingern machen. Dann die App in den Hintergrund, über quick actions ein anderes Projekt geöffnet, auch dort muss ich den Doppelklick mit 2 Fingern machen. Wieder die App in den Hintergrund und dann das Projekt zu Hause öffnen. Wieder nur ein weißer Bildschirm. Doppelklick, dann wirds geladen.

**Comment by cn72** [comment]
Hab jetzt mal ein anderes Samsung genommen, auf dem noch die iobroker vis (nicht visu) installiert war genommen. Damit klappt es sowohl lokal als auch via pro. Dann die neue Version (visu, nicht die Beta genommen) und 2 Projekte angelegt. Gleiches Verhalten wie bei meinem Handy. Es kommt bei der pro-Verbindung ein weißer Bildschirm bei beiden Projekten

**Comment by foxriver76** [comment]
oh man strange, habe noch ne wage vermutung die aber nicht erklären würde warum es bei vielen anderen und mir geht.

Bitte mal die APK probieren https://easyupload.io/slwm6v (sorry aber offizieller test ist immer nen rattenschwanz + wartezeit)

**Comment by cn72** [comment]
Leider klappt es damit auch nicht. Gleiches Verhalten.
Telefon Neustart (man weiß ja nie...) brachte auch keine Abhilfe.

**Comment by cn72** [comment]
War grade bei einem Bekannten. Der hat ein Samsung S22. Hatte die 1.0.35 drauf, damit das gleiche Fehlerverhalten. Auch nach dem Update auf 1.0.36 kommt bei der PRO Verbindung erst ein weißer Bildschirm und nach Doppelklick mit den 2 Fingern wird die VIS angezeigt.

**Comment by cn72** [comment]
Hast du evtl. noch eine ältere Version 1.0.34 oder früher um mal zu schauen ob es damit dann funktioniert. Wer weiß, was Samsung bei seinen Updates alles verbiegt...... Da sind ja in der letzten Zeit auch einige gekommen.

**Comment by cn72** [comment]
Hab die App grade mal auf einem Samsung S7 installiert. Dort genau das gleiche Verhalten......

**Comment by foxriver76** [comment]
Ich habe dir mal Credentials zu meinem Test Account geschickt. Probier den mal bitte.

**Comment by foxriver76** [comment]
Also habe es jetzt wieder mit der aktuellen offiziellen Version zusätzlich auf einem Samsung Galaxy S10 probiert. Funktioniert komplett problemlos..

**Comment by foxriver76** [comment]
Okay, dann blöde Frage bevor ich mir weiter einen Wolf suche, kannst du mir auf einen der Pro Zugänge die das Problem haben Zugriff geben? Gerne vorher das Passwort abändern und danach auch wieder.

**Comment by foxriver76** [comment]
Ansonten ich habe Web 6.2.3 laufen, auf einem der Pro Accounts diese Einstellungen:

![grafik](https://github.com/foxriver76/ioBroker-Visu-App/assets/25484431/0f560311-bcd6-4dee-8913-0ebdd2dcf225)

Cloud 4.4.1
vis 1.5.4

**Comment by cn72** [comment]
hast ne Mail,
Passwort habe ich geändert, Cloud Adapter auch, Backup ist grade durch....

**Comment by foxriver76** [comment]
Danke, unter iOS greift er 1A zu mit dem Galaxy kann ich es nachstellen.

**Comment by foxriver76** [comment]
next try: https://easyupload.io/1pfhd7

**Comment by cn72** [comment]
Sieht schon viel besser aus, es kommt jetzt jedesmal Connection to Server / Loading Values.... / Lade Widget-Sätze...
Aber: Beim Verein geht es nur weiter wenn bei Lade Widget Sätz in Klammern die 7 steht, für zu Hause wenn dort in Klammern 16 steht und bei der Arbeit, wenn dort in Klammern die 8 steht. Meistens wird dort immer die Zahl vom zuletzt geöffnetr VIS angezeig.
Beispiel: ich öffne die Vereins VIS, schließe ich dann und öffne die Arbeit VIS steht dort auch in Klammern 7 und es geht nicht weiter. Entweder nochmal schließen oder in die Einstellung oder Doppelklick. Nicht immer klappt es dann auf anhieb. Sobald dann die (für die Arbeit 8) richtige Zahl drin steht geht es. Dann kann ich auch nach dem schließen und neu öffnen direkt auf diese VIS zugreifen.

**Comment by foxriver76** [comment]
next try https://easyupload.io/r5tu8s

**Comment by cn72** [comment]
Klappt, jetzt dreht das Logo etwas länger dafür zu 100% immer die VIS geladen. Hab sämtlich Varianten durch die APP zu starten...

**Comment by foxriver76** [comment]
Hallelujah, was lange währt ... 

Dan bitte wieder die Zugangsdaten ändern.

**Comment by foxriver76** [comment]
App ist so eingereicht für iOS und Android. Hoffe klappt dann alles bei mir zumindest auf beiden Systemen problemlos.

**Comment by cn72** [comment]
OK, hab jetzt die offizelle Version wieder installiert. Passwort ist geändert. Wenn die 1.0.37 da ist schließe ich hier....

**Comment by foxriver76** [comment]
Okay, dann mache ich nochmal auf ;-)

**Comment by cn72** [comment]
Mit Version 1.0.37 funktioniert es jetzt auf Android, besten Dank für die Mühe....
