### ISSUE TITLE
[BUG] No longer loads http

### ISSUE THREAD

**Issue by udondan** [foxriver76/ioBroker-Visu-App#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After the recent update to 1.0.32 the app no longer loads my vis, as it apparently now expects https.

> The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.

![IMG_1902](https://github.com/foxriver76/ioBroker-Visu-App/assets/6443408/15de565c-e7a2-4caf-89d7-19e3cc26f5d2)

### Expected Behavior

Load vis regardless of protocol.

### Which OS are you using?

iOS

### OS Version

17.3.1

### Device

iPhone 15 Pro Max

### App Version

1.0.32

**Comment by foxriver76** [comment]
can you show the configuration, I cannot replicate this using of course simple http urls for local access

**Comment by udondan** [comment]
Right, it might also be related to last nights iOS update...

I have no special configuration, all default. Should have mentioned: I only use my local connection, no cloud.

![IMG_1904](https://github.com/foxriver76/ioBroker-Visu-App/assets/6443408/1b8e2526-136e-4949-b718-bbcc0014ccbe)

**Comment by udondan** [comment]
I just tested on my wifes phone, she hasn't updated iOS yet. Same problem with iOS 17.2.1.

**Comment by udondan** [comment]
OK, I think I got it. When I use the IP of my raspberry, it works. When I use the hostname, which is relsoved through my local DNS, it expects HTTPS.

But then all resources which are references via http://rasp.pi:8089/... in my vis are not loaded, e.g. all flot diagrams.

**Comment by foxriver76** [comment]
Hm okay, that maybe brings us one point closer, but not sure why the webview cares about this now..

**Comment by Strobelix80** [comment]
Same here
Local dns fails
Ip works

**Comment by foxriver76** [comment]
Hm.. we have `NSAllowsArbitraryLoads` set to `YES` which should disable the whole `ATS`. However, according to the message the `ATS` policy requires it, really strange.

**Comment by foxriver76** [comment]
Due to some dependency issues it was not set correctly in the output, `1.0.33` will fix it and is currently being checked by Apple

**Comment by foxriver76** [comment]
Does it work?

**Comment by udondan** [comment]
Review went fast. Confirming, 1.0.33 is working nicely.

**Comment by foxriver76** [comment]
Yes Apple is way faster with reviews then google play most of the time 😬

thanks for the confirmation
