### ISSUE TITLE
[BUG] Geofence-Koordinaten im Portät Modus verwirrend :) 

### ISSUE THREAD

**Issue by cavernerg** [foxriver76/ioBroker-Visu-App#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Wenn ich einen Standort auswähle für die Geofences, dann werden Längen und Breitengrad anschließend angezeigt. Allerdings sieht man nicht die Zahl "von links" sondern nur die letzten Ziffern. Im Porträtmodus bei Android führt das dazu , dass man statt 51.221234124144  dann nur noch "4124144" sieht. 
Hat mich jetzt am Anfang etwas verwirrt :) 

### Expected Behavior

Die Anzeige von Längen- und Breitengrad wird hinten beschnitten und nicht vorn. 

### Which OS are you using?

Android

### OS Version

12

### Device

Huawei P30 Pro

### App Version

1.1.9

**Comment by cavernerg** [comment]
![Screenshot_20240504_144441.jpg](https://github.com/foxriver76/ioBroker-Visu-App/assets/62744005/74411455-f1d7-44c6-9472-4cc04004d16f)

![Screenshot_20240504_144419_com.iobroker.visu.jpg](https://github.com/foxriver76/ioBroker-Visu-App/assets/62744005/7261a2d3-8d2c-4ea8-b83b-6b32b3ad6319)

Screenshots for demonstration

**Comment by foxriver76** [comment]
Understood yes should better show the first letters and numbers if too long

**Comment by foxriver76** [comment]
fixed will be released with v1.2.0 end of month
