### ISSUE TITLE
Add guide to disable battery optimization for geofencing

### ISSUE THREAD

**Issue by cavernerg** [foxriver76/ioBroker-Visu-App#40]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Feature description

This is just for you to minimize your support efforts: I would add a prominent link to https://dontkillmyapp.com/ on geofencing tab plus a popup on first activation of the feature

**Comment by foxriver76** [comment]
Thanks, that's are very interesting page, I will add it to the How-To overlay for the android app

**Comment by foxriver76** [comment]
will be part of 1.2.0
