### ISSUE TITLE
Vis2 im Browser nicht mehr aufrufbar

### ISSUE THREAD

**Issue by ChrisDei** [foxriver76/ioBroker-Visu-App#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Vis2 ist in Safari/Chrome weder im Editor noch im Runtime aufrufbar, nicht aus der Instanzenliste und auch auch nicht direkt per http://192.168.179.95:8082/vis-2/edit.html. Es erscheint nur ganz kurz das ioBroker-Zeichen, danach bleibt das Fenster weiß. 

Gestern hatte ich versehentlich eine View gelöscht, die ich heute einzeln restoren wollte. Nachdem das nicht geklappt hat, habe ich mit Backitup den Stand von gestern wieder eingespielt. 
Das Verhalten ändert sich auch nicht, wenn ich Projektverzeichnis und /oder Projektfiles rename (/opt/iobroker/iobroker-data/files/vis-2.0). Erstaunlicherweise läuft Vis2 auf dem iPhone noch so, wie es sollte. Vermutlich liegt es also nicht an meinen Views. In den ioBroker-Protokollen sehe ich keine Fehlermeldungen. In älteren Threads wurde ein Problem mit dem Metro-Widget (bei mir installiert) erwähnt, das aber gefixt ist. 
Ich habe keine Idee mehr, wo ich noch gucken / was ich noch machen könnte.

### Which OS are you using?

iOS

### OS Version

17.5.1

### Device

iPhone 14 Plus

### App Version

5.0.19

**Comment by foxriver76** [comment]
Bitte im vis 2 Tempo eröffnen hier gehts nur um die Mobiel App

**Comment by ChrisDei** [comment]
Sorry, bin noch dabei mich zurechtzufinden... Ist jetzt hier: https://github.com/ioBroker/ioBroker.vis-2/issues/451
