### ISSUE TITLE
[BUG] Reloadmöglichkeit fehlt bei VPN Aufbau

### ISSUE THREAD

**Issue by micklafisch** [foxriver76/ioBroker-Visu-App#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Wenn das CON nur etwas länger braucht um sich erfolgreich zu verbinden kommt die Meldung „NSURLErrorDomain“. Bei diesem Punkt gibts kein zurück.

### Expected Behavior

Button unter dem bestehenden Problem melden mit „erneut versuchen“

### Steps To Reproduce

VPN Aufbau mehrfach testen, beim schnellen wechsel zur App kommt gelegentlich der Fehler

### Which OS are you using?

iOS

### OS Version

17.5.1

### Device

iPhone 13 pro

### App Version

1.2.0

### Anything else?

![IMG_9042](https://github.com/user-attachments/assets/dbf53c2e-72a1-4e0a-b7cf-c312e4c6f634)

**Comment by foxriver76** [comment]
Lädt er dann nicht automatisch neu sobald der VPN da ist?

**Comment by micklafisch** [comment]
Nein, ich habe VPN bei mir über das iOS Kurzbefehlsystem gelöst. Wenn App geöffnet wird dann starte VPN.

**Comment by foxriver76** [comment]
Ja wir hatten das hier schon mal https://github.com/foxriver76/ioBroker-Visu-App/issues/35

Du musst der App mitteilen, dass es einen Unterscheid gibt zwischen lokalem Zugriff und externen Zugriff. z. .B bei Extern die gleichen Daten eintragen wie bei Lokal, aber auf jeden Fall was auswählen. Dann VPN Erkennung aktivieren in den App-Einstellungen und er sollte merken sobald der VPN an ist und neu laden.

**Comment by foxriver76** [comment]
Ja unter VPN Erkennung gibt es "immer VPN nutzen" das ist die Option um das Popup zu umgehen.

**Comment by micklafisch** [comment]
ahhh ok ich habe unter diesem Punkt etwas anderes interpretiert.

Danke vielmals, Thema erledigt
