### ISSUE TITLE
[FEATURE] IOS: Option to disable access to settings via 3 finger click

### ISSUE THREAD

**Issue by KoMa1978** [foxriver76/ioBroker-Visu-App#6]
The options should be added to Settings / ioBroker Visu like it is default in IOS. 

Also there should be an option to disable access to settings via 3 finger click. At the moment it is possible to access and change setting even if guided access (Geführter Zugriff) is enabled. This is not wanted on a wall mounted iPad for example.

**Comment by foxriver76** [comment]
As there is no such alternative for Android, in the short term it is not planned to move it into the system settings. However with the upcoming version, you will be able to protect the settings via your devices biometrics authentication, getting you at least a bit closer to your goal. I hope this also helps for your use case.
