### ISSUE TITLE
[FEATURE] Per State das Display abschalten

### ISSUE THREAD

**Issue by Standarduser** [foxriver76/ioBroker-Visu-App#7]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Feature description

Die App läuft auf meinem iPad dauerhaft im Vordergrund „Display nicht abschalten == True), bei Abwesenheit soll es jedoch ausgeschaltet sein. Dies würde ich gerne automatisieren, sodass das Tablet beim Verlassen des Hauses gesperrt wird.

Das Sperren des iPads könnte über einen State mit der Rolle Button realisiert werden. Das Aufwecken des iPads bei Rückkehr soll über den geführten Zugriff erfolgen.

**Comment by Standarduser** [comment]
Das würde meine Anforderungen vollkommen erfüllen und war tatsächlich auch mein erster Gedanke. Entweder per Button für eine gewisse Zeit abschalten, oder aber die Funktion generell per State ein-/ausschalten. In Kombination mit dem Life-Bit und dem geführten Zugriff hätte man das iPad dann eigentlich ziemlich gut unter Kontrolle. 

Danke

**Comment by foxriver76** [comment]
Keep Awake wird man mit der nächsten Version deaktivieren können.

**Comment by Standarduser** [comment]
Vielen Dank :)
