### ISSUE TITLE
[FEATURE] Wert des Helligkeitssensors als State

### ISSUE THREAD

**Issue by Standarduser** [foxriver76/ioBroker-Visu-App#8]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Feature description

Falls möglich wäre ich sehr dankbar, den Wert des Helligkeitssensors als State in ioBroker zu haben, um diesen in Automationen verwenden zu können

**Comment by foxriver76** [comment]
Seems like Apple does not allow apps to do so according to https://github.com/react-native-sensors/react-native-sensors/issues/319

**Comment by foxriver76** [comment]
Other ressource: https://docs.expo.dev/versions/latest/sdk/light-sensor/ (also only available for Android)

**Comment by Standarduser** [comment]
That's a pity but ok. Thank you
