### ISSUE TITLE
[FEATURE] Life-Bit

### ISSUE THREAD

**Issue by Standarduser** [foxriver76/ioBroker-Visu-App#9]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Feature description

Ich bitte um das Einfügen eines Life-Bits um erkennen zu können, ob die Visualisierung läuft und in Scripten darauf reagieren zu können, etwa dass Meldung dann per Telegram übermittelt werden. 

Im industriellen Umfeld werden Life-Bits in der Regel so realisiert, dass die Visualisierung ein Bit (hier State) auf True setzt und die Automation diesen auf False. Anschließend setzt die Visualisierung das Bit wieder auf True, usw. Wenn es über längere Zeit keine Zustandsänderung gibt, ist die Visualisierung tot und man reagiert entsprechend.

Eine Verzögerung, bis die Visualisierung das Bit setzt, zwischen 1-5 Sekunden scheint mir ein sinnvoller Wert zu sein. 

Vielen Dank

**Comment by foxriver76** [comment]
Should be possible, we can use the expire functionality of `setState`

like `servConn.setState('vis.0.iPad.alive', { val: true, ack: true, expire: 60 })` and setting every 30 seconds in interval. So it only will be `false` if no connection for 60 seconds.

**Comment by Standarduser** [comment]
This sounds great, thank you!

**Comment by foxriver76** [comment]
It is now implemented and will be part of the next version.
